apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-sim
  labels:
    app: trading-sim staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-sim staging
  template:
    metadata:
      labels:
        app: trading-sim staging
    spec:
      containers:
      - name: trading-sim
        image: yemmy03/trading-sim-app
        ports:
        - containerPort: 3000
        envFrom:
      - configMapRef:
          name: trading-sim-config 


